### ISSUE TITLE
Update MySQL manager script to latest datasets

### ISSUE THREAD

**Issue by asclines** [CodeSpaceHQ/SDA#13]
## Tasks
- [x] Once #10 has been closed, perform any required modifications
- [ ] Add enumerators for the tables and their attributes. [Python 3 Enumerators](https://docs.python.org/3/library/functions.html#enumerate)
- [ ] Create Select Methods

### Select Methods
Since the purpose of the MySQL manager script is to hide all actual MySQL commands from the higher up modules, all MySQL commands need to be here. First up, _Selection_.  
This method needs to be able to take in:
- tables
- select by attributes
- conditions on attributes

Tables and attributes should always be referenced by their respective enums.

**Comment by asclines** [comment]
Just to the reasoning is out here:
#### Enums
So that in the event that tables or attributes names change, that can be fixed here and the rest of the script will work.

#### Select
So the upper levels don't have to worry about the actual MySQL syntax. The reason I have the SQL method still there is so the higher up modules can still use actual SQL and algebra relations that will be determined outside of the code for the assignment.

**Comment by asclines** [comment]
Closing as we are no longer going this route.
